title = "Chill Utility"
languageCode = "en"
languageName = "English"
weight = 1

[params]
  description = "Manage your Discord servers in record time. Welcome to the next evolution in community building with Chill Utility! 🚀"
  displayName = "EN"
  isoCode = "en"
  weight = 1
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.webp"
  secondaryLogo = "img/logo.webp"
  copyright = "Chill Utility · Made with 💜"

[author]
  name = "Chill Utility Team"
  image = "img/cu-team-icon.png"
  headline = "Chill Utility Team"
  bio = "As chill than creative"
  links = [
    { discord = "https://discord.gg/chillfr" }
  ]
